import React, { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

export default function ListForm({ onListFormSubmit }) {
  const [listText, setListText] = useState('');

  // Simple form submission, prevent page from reloading,
  // if there is no text, return out of the function,
  // otherwise, call the method that was passed down from our parent and send up a simple
  // object with an ID generated by uuidv4 and the text that the user entered in
  // lastly, reset the text in the form input
  const onFormSubmit = (event) => {
    event.preventDefault();
    if (!listText) {
      return false;
    }

    onListFormSubmit({
      id: uuidv4(),
      text: listText
    });
    setListText('');
  }

  return (
    <form className="flex flex-row my-5 w-full" onSubmit={onFormSubmit}>
      <input
        className="flex-grow rounded-md p-3 bg-gray-100 mr-3"
        type="text"
        placeholder="Enter some text!"
        value={listText}
        onChange={(event) => setListText(event.target.value)} />
      <button
        className="rounded-md py-3 px-10 text-white bg-black"
        type="submit">
        Submit
      </button>
    </form>
  )
}
